### ISSUE TITLE
Merging this into original

### ISSUE THREAD

**Issue by ThatTimothy** [rileyaft/RoNewFirefoxed#2]
Thanks for your work! I'll be merging this into the main repo through ThatTimothy/RoNew#16.

I'd appreciate it if you could take down your add-on when that occurs, so there isn't any confusion!

Again, thanks for your contributions!

**Comment by ThatTimothy** [comment]
Alright, the official version is now live! Try the button below:

[![Firefox Extension](https://img.shields.io/amo/v/RoNew?label=Firefox%20add-ons&logo=firefox-browser&logoColor=white&style=for-the-badge&color=FF7139&cacheSeconds=3600)](https://addons.mozilla.org/addon/ronew/)

**Comment by rileyaft** [comment]
sorry for the late response, will be taking down now!
